title: James Corley
theme: minima
show_excerpts: true
author: James Corley
location: Dallas, Texas, United States
email: root@jamescorley.me
linkedin_username: james-corley
github_username: jamestcorley
excerpt_separator: <!-- end excerpt -->
